[package]
name = "xbim"
version = "1.0.0"
edition = "2021"
include = ["LICENSE.md", "**/*.rs", "Cargo.toml"]
authors = ["XodiumSoftware <https://xodium.org/>"]
description = "All-in solution to BIM models, written in Rust."
license = "AGPL-3.0"
repository = "https://github.com/XodiumSoftware/xBIM"
homepage = "https://xodium.org/"
publish = false

[package.metadata.docs.rs]
all-features = true

[profile.release]
opt-level = 2

[profile.dev]
opt-level = 2

[dependencies]
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
axum = "0.8.0-rc.1"
http = "1.2.0"
tracing-subscriber = "0.3.19"
serde = { version = "1.0.216", features = ["derive"] }
