name: Xodium CI/CD - Check Branches

on:
  pull_request_target:
    types: [ opened, reopened, synchronize, edited, ready_for_review ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - id: check_branches
        name: Check Branches
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "$HEAD_REF" != "dev" ] && [ "$BASE_REF" == "main" ]; then
            echo "Merge requests to main branch are only allowed from dev branch."
            exit 1
          fi
        shell: bash