name: Xodium CI/CD
run-name: "Xodium CI/CD"

# TODO: redo workflow to work with framework.

on:
  push:
    branches: [ main ]
    paths:
      - 'xbim/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.upload_artifact.outputs.artifact-url }}
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: setup_rust
        name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      #      - id: install_deps
      #        name: Install Dependencies
      #        run: |
      #          sudo apt update && sudo apt install clang
      #          cargo install trunk
      #          rustup target add wasm32-unknown-unknown
      #
      #      - id: build_artifact
      #        name: Build Artifact
      #        run: trunk build
      #        working-directory: xbim

      - id: install_toml_cli
        name: Install toml-cli
        run: cargo install toml-cli

      - id: get_version
        name: Get Version
        run: echo "VERSION=$(toml get xbim/Cargo.toml package.version)" >> $GITHUB_OUTPUT

      - id: upload_artifact
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xbim
          path: xbim/dist/

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - id: download_artifact
        name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: xbim

      - id: setup_rust
        name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - id: run_tests
        name: Run Tests
        run: cargo test --all

  release:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.create_release.outputs.url }}
    steps:
      - id: download_artifact
        name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: xbim

      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ contains(github.event.head_commit.message, '.draft') }}
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, '.pre') }}
          tag_name: ${{ needs.build.outputs.VERSION }}
